services:

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    restart: unless-stopped


  tempo:
    image: grafana/tempo:3.0.0
    container_name: tempo

    command:
      - "-target=all"
      - "-config.file=/etc/tempo.yaml"

    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - tempo-data:/var/tempo

    ports:
      - "3200:3200"

    expose:
      - "4317"
      - "4318"

    restart: unless-stopped


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.156.0
    container_name: otel-collector

    command:
      - "--config=/etc/otelcol/config.yaml"

    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro

    ports:
      - "4317:4317"
      - "4318:4318"

    expose:
      - "9464"

    depends_on:
      - tempo
      - elasticsearch

    restart: unless-stopped


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    restart: unless-stopped


  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus
      - tempo
      - elasticsearch

    restart: unless-stopped


  telemetrygen:
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:v0.150.0

    profiles:
      - test

    command:
      - traces
      - --otlp-insecure
      - --rate
      - "20"
      - --duration
      - "5s"
      - --otlp-endpoint
      - "otel-collector:4317"

    depends_on:
      - otel-collector


volumes:
  prometheus-data:
  tempo-data:
  grafana-data:
  elasticsearch-data: